from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum


class EventType(str, Enum):
    LOGIN_SUCCESS = "login_success"
    LOGIN_FAILURE = "login_failure"
    UNKNOWN = "unknown"


class Severity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


@dataclass
class LogEvent:
    """
    Normalized representation of an authentication event.
    """

    timestamp: datetime
    username: str
    source_ip: str
    event_type: EventType
    raw_log: str


@dataclass
class Finding:
    """
    Represents a security finding generated by a detector.
    """

    detection_type: str
    severity: Severity
    risk_score: int
    source_ip: str | None = None
    username: str | None = None
    description: str = ""
    evidence: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "detection_type": self.detection_type,
            "severity": self.severity.value,
            "risk_score": self.risk_score,
            "source_ip": self.source_ip,
            "username": self.username,
            "description": self.description,
            "evidence": self.evidence,
        }